package cn.tmq.service.notebook.mapper;

import cn.tmq.service.notebook.entity.MBlogs;

public interface MBlogsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_blogs
	 * @mbg.generated  Wed Apr 03 23:28:58 CST 2019
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_blogs
	 * @mbg.generated  Wed Apr 03 23:28:58 CST 2019
	 */
	int insert(MBlogs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_blogs
	 * @mbg.generated  Wed Apr 03 23:28:58 CST 2019
	 */
	int insertSelective(MBlogs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_blogs
	 * @mbg.generated  Wed Apr 03 23:28:58 CST 2019
	 */
	MBlogs selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_blogs
	 * @mbg.generated  Wed Apr 03 23:28:58 CST 2019
	 */
	int updateByPrimaryKeySelective(MBlogs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_blogs
	 * @mbg.generated  Wed Apr 03 23:28:58 CST 2019
	 */
	int updateByPrimaryKey(MBlogs record);
}