package cn.tmq.service.notebook.entity;

import java.util.Date;

public class MNotes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_notes.id
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_notes.user_id
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_notes.category_id
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_notes.title
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_notes.content
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_notes.display_content
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    private String displayContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_notes.update_time
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_notes.insert_time
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    private Date insertTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_notes.id
     *
     * @return the value of m_notes.id
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_notes.id
     *
     * @param id the value for m_notes.id
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_notes.user_id
     *
     * @return the value of m_notes.user_id
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_notes.user_id
     *
     * @param userId the value for m_notes.user_id
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_notes.category_id
     *
     * @return the value of m_notes.category_id
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_notes.category_id
     *
     * @param categoryId the value for m_notes.category_id
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_notes.title
     *
     * @return the value of m_notes.title
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_notes.title
     *
     * @param title the value for m_notes.title
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_notes.content
     *
     * @return the value of m_notes.content
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_notes.content
     *
     * @param content the value for m_notes.content
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_notes.display_content
     *
     * @return the value of m_notes.display_content
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    public String getDisplayContent() {
        return displayContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_notes.display_content
     *
     * @param displayContent the value for m_notes.display_content
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    public void setDisplayContent(String displayContent) {
        this.displayContent = displayContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_notes.update_time
     *
     * @return the value of m_notes.update_time
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_notes.update_time
     *
     * @param updateTime the value for m_notes.update_time
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_notes.insert_time
     *
     * @return the value of m_notes.insert_time
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_notes.insert_time
     *
     * @param insertTime the value for m_notes.insert_time
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }
}