package cn.tmq.service.login.mapper;

import cn.tmq.service.login.entity.MUserDetails;

public interface MUserDetailsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_user_details
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_user_details
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	int insert(MUserDetails record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_user_details
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	int insertSelective(MUserDetails record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_user_details
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	MUserDetails selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_user_details
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	int updateByPrimaryKeySelective(MUserDetails record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_user_details
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	int updateByPrimaryKey(MUserDetails record);
}