package cn.tmq.service.login.mapper;

import cn.tmq.service.login.entity.MUsers;

public interface MUsersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_users
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_users
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	int insert(MUsers record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_users
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	int insertSelective(MUsers record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_users
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	MUsers selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_users
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	int updateByPrimaryKeySelective(MUsers record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_users
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	int updateByPrimaryKey(MUsers record);
}