package cn.tmq.service.notebook.mapper;

import cn.tmq.service.notebook.entity.MNotes;

public interface MNotesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_notes
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_notes
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    int insert(MNotes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_notes
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    int insertSelective(MNotes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_notes
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    MNotes selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_notes
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    int updateByPrimaryKeySelective(MNotes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_notes
     *
     * @mbg.generated Wed Apr 10 22:56:38 CST 2019
     */
    int updateByPrimaryKey(MNotes record);
}