package cn.tmq.service.login.entity;

import java.util.Date;

public class MUserDetails {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column m_user_details.id
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column m_user_details.sex
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	private Integer sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column m_user_details.age
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column m_user_details.phone
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	private Integer phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column m_user_details.email
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column m_user_details.address
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column m_user_details.update_time
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column m_user_details.insert_time
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	private Date insertTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_user_details.id
	 * @return  the value of m_user_details.id
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_user_details.id
	 * @param id  the value for m_user_details.id
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_user_details.sex
	 * @return  the value of m_user_details.sex
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_user_details.sex
	 * @param sex  the value for m_user_details.sex
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_user_details.age
	 * @return  the value of m_user_details.age
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_user_details.age
	 * @param age  the value for m_user_details.age
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_user_details.phone
	 * @return  the value of m_user_details.phone
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	public Integer getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_user_details.phone
	 * @param phone  the value for m_user_details.phone
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	public void setPhone(Integer phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_user_details.email
	 * @return  the value of m_user_details.email
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_user_details.email
	 * @param email  the value for m_user_details.email
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_user_details.address
	 * @return  the value of m_user_details.address
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_user_details.address
	 * @param address  the value for m_user_details.address
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_user_details.update_time
	 * @return  the value of m_user_details.update_time
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_user_details.update_time
	 * @param updateTime  the value for m_user_details.update_time
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_user_details.insert_time
	 * @return  the value of m_user_details.insert_time
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	public Date getInsertTime() {
		return insertTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_user_details.insert_time
	 * @param insertTime  the value for m_user_details.insert_time
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}
}