package cn.tmq.service.login.entity;

import java.util.Date;

public class MUsers {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column m_users.id
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column m_users.account
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	private String account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column m_users.password
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column m_users.level
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	private String level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column m_users.update_time
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column m_users.insert_time
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	private Date insertTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_users.id
	 * @return  the value of m_users.id
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_users.id
	 * @param id  the value for m_users.id
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_users.account
	 * @return  the value of m_users.account
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_users.account
	 * @param account  the value for m_users.account
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_users.password
	 * @return  the value of m_users.password
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_users.password
	 * @param password  the value for m_users.password
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_users.level
	 * @return  the value of m_users.level
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	public String getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_users.level
	 * @param level  the value for m_users.level
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	public void setLevel(String level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_users.update_time
	 * @return  the value of m_users.update_time
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_users.update_time
	 * @param updateTime  the value for m_users.update_time
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column m_users.insert_time
	 * @return  the value of m_users.insert_time
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	public Date getInsertTime() {
		return insertTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column m_users.insert_time
	 * @param insertTime  the value for m_users.insert_time
	 * @mbg.generated  Wed Apr 10 22:38:46 CST 2019
	 */
	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}
}